const P={},me=pp(pid0())||DB.people[0];
const QA=h=>[['How rested do you feel?',h.rq],['How is your workload?',h.load],['How has your mood been?',h.m]];
const rqBtn=`<button class="btn p" onclick="reqModal()"><i class="fa-solid fa-hand-holding-heart"></i> Request Welfare Support</button>`;
const cards=a=>a.map(c=>`<div class="card hv"><i class="ic fa-solid ${c[0]}"></i><h3>${c[1]}</h3><p>${c[2]||''}</p></div>`).join('');
const sec=(id,t,s,c,n=3)=>`<section class=sec id=${id}><h2>${t}</h2><p>${s}</p><div class="g g${n}">${cards(c)}</div></section>`;
const wTrend=(id=me.id)=>[...pp(id).tr.slice(0,4),W(id)];

/* ---------- Landing ---------- */
P.landing=()=>{
 document.body.innerHTML=`<header class=nav><a class=logo href="index.html"><i class="fa-solid fa-heart" style="color:var(--in)"></i> Take My Care</a><nav><a href="#why">Why It Matters</a><a href="#how">How It Works</a><a href="#features">Features</a><a href="#tech">Technology</a><a href="#benefits">Benefits</a><a href="#privacy">Help</a></nav><div class=row><button class=btn onclick="toggleTheme()"><i class="fa-solid fa-circle-half-stroke"></i></button><a class=btn href="login.html">Login</a><a class="btn p" href="login.html">Get Started</a></div></header>
 <section class=hero><div><h1>Take My Care.</h1><h2>Support before stress grows.</h2><p>An AI-assisted welfare monitoring platform designed to help uniformed personnel and welfare teams identify changing wellbeing patterns early and connect people with appropriate support.</p><div class=row><a class="btn p" href="login.html">Explore the Portal</a><a class=btn href="#how">See How It Works</a></div><div class=chips><span>Privacy-first</span><span>Role-based access</span><span>AI-assisted insights</span><span>Human-centered support</span></div></div>
 <div class=card style="backdrop-filter:blur(14px)"><div class="row sp"><div class=row><div class=av>A</div><div><b>Aarav Sharma</b><br><small>@PF-1042 · Unit C</small></div></div>${bd('LOW')}</div><h1 style="font-size:3rem;margin:1rem 0 0">78%<small style="font-size:14px"> wellness score</small></h1><div class=ch style="height:150px"><canvas id=hc></canvas></div><div class="row sp"><small>Recent check-in: 18 Sep · Good</small>${bd('ACCEPTED')}</div></div></section>
 ${sec('why','Why Take My Care?','Stress is easier to support when patterns are noticed early.',[['fa-clock','Stress can be noticed too late','Changes are often visible only after they have built up.'],['fa-eye','Manual observation varies','Different observers notice different things.'],['fa-pen','Self-reports miss patterns','A single answer rarely shows a changing trend.'],['fa-bed','Rest and workload are hard to track','Little signals add up across weeks.'],['fa-folder-open','Teams need organized history','Welfare officers need context, not scattered notes.'],['fa-hand-holding-heart','Support should be easy to ask for','Personnel can request a conversation in one tap.']])}
 <section class=sec id=how><h2>How it works</h2><p>Four simple steps.</p><div class="g g4">${['Check In|fa-clipboard-check','Understand|fa-chart-line','Request Support|fa-hand-holding-heart','Follow Up|fa-calendar-check'].map((x,i)=>`<div class="card hv"><div class=av style="margin-bottom:.8rem">${i+1}</div><h3><i class="fa-solid ${x.split('|')[1]}" style="color:var(--te)"></i> ${x.split('|')[0]}</h3></div>`).join('')}</div></section>
 ${sec('features','Features','Everything a welfare team needs in one place.',[['fa-brain','AI-assisted risk indication'],['fa-heart-pulse','Wellness check-ins'],['fa-clipboard-question','Question & answer history'],['fa-chart-line','Progress tracking'],['fa-id-badge','Personnel profile'],['fa-hand-holding-heart','Welfare requests'],['fa-inbox','Officer request management'],['fa-triangle-exclamation','Risk alerts'],['fa-calendar-check','Follow-up management'],['fa-chart-pie','Analytics'],['fa-bell','Notifications'],['fa-circle-half-stroke','Dark / light mode']])}
 ${sec('tech','Technology','Simple, proven, easy to extend.',[['fa-code','Frontend','HTML5, CSS3, JavaScript, Chart.js'],['fa-server','Backend','Python, Flask, REST API'],['fa-database','Database','MySQL'],['fa-microchip','AI','Python, Machine Learning, Scikit-learn'],['fa-cloud','Future deployment','Cloud / secure server']])}
 ${sec('benefits','Benefits','What changes for personnel and welfare teams.',['Earlier support','Better welfare visibility','Personalized follow-up','Historical progress','Organized welfare workflow','Privacy-aware access','Reduced manual workload','Human-centered intervention'].map(x=>['fa-circle-check',x]),4)}
 ${sec('privacy','Privacy & security','Wellbeing information stays with authorized people.',[['fa-user-lock','Role-based access'],['fa-shield-halved','Personnel data protection'],['fa-user-shield','Authorized officer access'],['fa-eye-slash','No public exposure of wellness information'],['fa-key','Secure authentication in production'],['fa-circle-info','AI output is an indication, not a medical diagnosis']])}
 ${sec('who','Who it is for','',['Uniformed Personnel|fa-user','Welfare Officers|fa-user-nurse','Police|fa-shield','Armed Forces|fa-flag','Emergency Responders|fa-truck-medical','Disaster Response Teams|fa-hands-holding-circle'].map(x=>[x.split('|')[1],x.split('|')[0]]))}
 <section class=cta><h2>Care should start before the crisis.</h2><a class="btn" style="color:#0b1b33;background:#fff" href="login.html">Enter Take My Care</a></section>
 <footer class="sec mu" style="text-align:center;font-size:13px">Take My Care · Smart India Hackathon · SIH26186 · AI-Based Predictive Personnel Stress and Welfare Monitoring System for Uniform Forces<br>This prototype is for welfare support and demonstration purposes. AI-assisted indicators are not medical diagnoses.</footer>`;
 C.line('hc',DB.trend.l,DB.trend.w,'#14b8a6');
};
P.login=loginPage;

/* ---------- Shared request flow ---------- */
function reqModal(){modal(`<h3>Request Welfare Support</h3><label>Support type<select id=rt><option>General welfare conversation</option><option>Workload/rest discussion</option><option>Follow-up</option><option>Other</option></select></label><label>Message (optional)<textarea id=rm rows=3></textarea></label><button class="btn p" onclick="sendReq()">Send Request</button>`)}
function sendReq(){const r=R.g();r.unshift({id:Date.now(),by:me.n,pid:me.id,unit:me.u,today:1,type:$('#rt').value,msg:$('#rm').value,status:'PENDING'});R.s(r);closeM();render();toast('Request sent. Status: PENDING')}
const qaModal=i=>{const h=hist()[i];modal(`<h3>Check-in · ${h.d}</h3>${QA(h).map(q=>`<p><b>${q[0]}</b><br>${q[1]}</p><br>`).join('')}<p>AI-assisted indication: ${bd(h.risk)}</p>`)};
const entry=(i,j)=>{const h=hist()[i],q=QA(h)[j];modal(`<h3>${q[0]}</h3><p><b>Recorded answer:</b> ${q[1]}</p><p><b>Date:</b> ${h.d}</p><p><b>Context:</b> Rest ${h.rest}, workload ${h.load}, mood ${h.m}.</p><p><b>AI-assisted indication:</b> ${bd(h.risk)}</p>`)};
function act(id,s){const r=R.g(),x=r.find(y=>y.id==id);x.status=s;R.s(r);if(s=='FOLLOW-UP'){const f=F.g();f.unshift({id:Date.now(),n:x.by,pid:x.pid,reason:x.type,created:'Today',due:'In 7 days',status:'Pending'});F.s(f)}closeM();render();toast({ACCEPTED:'Request accepted. Personnel has been notified.',DECLINED:'Request declined. Personnel has been notified.','FOLLOW-UP':'Follow-up requested. Personnel has been notified.'}[s])}
function review(id){const x=R.g().find(y=>y.id==id),p=DB.people.find(y=>y.id==x.pid),n=R.g().filter(y=>y.pid==x.pid&&y.status!='PENDING').length;modal(`<div class=row><div class="av xl">${x.by[0]}</div><div><h3>${x.by}</h3><small>@${x.pid} · ${x.unit}</small></div></div><p style="margin-top:1rem"><b>${x.type}</b><br>${x.msg||'No message provided.'}</p><p>Previous support records: ${n}<br>Recent indication: ${bd(p.risk.toUpperCase())}</p><div class=row style="margin-top:1rem"><button class="btn p" onclick="act(${x.id},'ACCEPTED')">Accept Request</button><button class=btn onclick="act(${x.id},'FOLLOW-UP')">Request Follow-up</button><button class=btn onclick="act(${x.id},'DECLINED')">Decline</button></div>`)}
const rc=x=>`<div class="card req hv"><div class=row><div class=av>${x.by[0]}</div><div style="flex:1"><b>${x.by}</b><br><small>@${x.pid} · ${x.unit}</small></div>${bd(x.status)}</div><p><b>${x.type}</b><br><small>${x.msg||''}</small></p>${x.status=='PENDING'?`<div class=row><button class=btn onclick="review(${x.id})">Review</button><button class="btn p" onclick="act(${x.id},'ACCEPTED')">Accept</button><button class=btn onclick="act(${x.id},'DECLINED')">Decline</button></div>`:''}</div>`;
const flow=s=>`<small class=mu>Sent → Pending → ${s=='PENDING'?'<b>Awaiting review</b>':bd(s)}</small>`;

/* ---------- Personnel ---------- */
P['p-dashboard']=()=>{const h=hist(),a=R.g().filter(r=>r.pid==me.id&&['PENDING','ACCEPTED','FOLLOW-UP'].includes(r.status)).length;
 shell('personnel','dashboard','Good morning, '+me.n.split(' ')[0],`<div class="g g4">${stat('Current Indication',bd(h[0].risk.toUpperCase()),'fa-shield-heart')}${stat('Wellness Score',W()+'%','fa-heart-pulse')}${stat('Check-ins',me.ci+h.length-4,'fa-clipboard-check')}${stat('Support',a+' Active','fa-hand-holding-heart')}</div><div class="g g2b"><div class=card><h3>Wellness Progress</h3><div class=ch><canvas id=c1></canvas></div></div><div class=card><h3>Need to talk to someone?</h3><p class=mu style="margin:.6rem 0 1rem">Send a request to an authorized welfare officer any time.</p>${rqBtn}</div></div><div class=card><h3>Recent check-ins</h3>${tbl(['Date','Mood','Rest','Workload','Risk','Support',''],h.slice(0,5).map((x,i)=>[x.d,x.m,x.rest,x.load,bd(x.risk),x.sup,`<button class=btn onclick="qaModal(${i})">View Q&A</button>`]))}</div>`);
 C.line('c1',DB.trend.l,wTrend());};
const profile=(role,p,h)=>`<div class=card style="padding:0;overflow:hidden"><div class=banner></div><div class="pf row" style="align-items:flex-end"><div class="av xl">${p.n[0]}</div><div style="padding-top:50px"><h2>${p.n}</h2><small>@${p.id} · ${p.u} · ${p.r}</small></div></div><div class=row style="padding:1rem 1.3rem">${role=='personnel'?`<button class=btn onclick="toast('Profile editing is enabled in the full version')">Edit Profile</button>${rqBtn}`:`<button class="btn p" onclick="mkFu('${p.id}')">Create Follow-up</button>`}</div></div><div class="g g4" style="margin-top:1rem">${stat('Wellness',W(p.id)+'%','fa-heart-pulse')}${stat('Check-ins',p.ci+h.length-4,'fa-clipboard-check')}${stat(role=='personnel'?'Week Streak':'Indication',role=='personnel'?p.st:bd(p.risk.toUpperCase()),'fa-fire')}${stat('Support Records',p.sr,'fa-hand-holding-heart')}</div>`;
const qaRows=h=>tbl(['Date','Question','Answer','Indication'],h.flatMap(x=>QA(x).map(q=>[x.d,q[0],q[1],bd(x.risk)])));
P['p-profile']=()=>{const h=hist();shell('personnel','profile','My Profile',profile('personnel',me,h)+tabs(['Overview','Progress','Wellness','Q&A History','Support'],[`<div class="g g2"><div class=card><h3>Wellness trend</h3><div class=ch><canvas id=c1></canvas></div></div><div class=card><h3>Recent activity</h3>${h.slice(0,4).map(x=>`<p>${x.d} · Check-in · ${bd(x.risk)}</p>`).join('')}</div></div>`,tbl(['Date','Wellness'],h.map(x=>[x.d,x.w+'%'])),tbl(['Date','Mood','Rest','Workload'],h.map(x=>[x.d,x.m,x.rest,x.load])),qaRows(h),tbl(['Type','Status'],R.g().filter(r=>r.pid==me.id).map(r=>[r.type,bd(r.status)]))]));C.line('c1',DB.trend.l,wTrend())};
P['p-wellness']=()=>{const q=(k,t)=>`<p><b>${t}</b></p>${OPT[k].map(o=>`<label class=opt><input type=radio name=${k} value="${o}" ${o==OPT[k][1]?'checked':''}><span>${o}</span></label>`).join('')}<br><br>`;
 shell('personnel','wellness','Wellness Check-in',`<div class=card style="max-width:720px"><h2>How are you doing today?</h2><br>${q('rest','1. How rested do you feel?')}${q('load','2. How is your workload?')}${q('mood','3. How has your mood been?')}<label>4. Optional message<textarea rows=3></textarea></label><button class="btn p" onclick="saveCI()">Save Check-in</button><p class=mu style="margin-top:1rem;font-size:13px">AI-assisted indicators are intended to support welfare review and are not medical diagnoses.</p></div>`)};
function saveCI(){const v=k=>document.querySelector(`input[name=${k}]:checked`).value,ix=k=>OPT[k].indexOf(v(k)),s=ix('rest')+ix('load')+ix('mood'),risk=riskOf(s),w=W(),nw=Math.max(30,Math.min(95,w+(risk=='Low'?2:risk=='Medium'?-2:-5))),h=hist();
 h.unshift({d:new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short'}),m:v('mood'),rq:v('rest'),rest:[8,7,6,5][ix('rest')]+'h',load:v('load'),risk,w:nw,sup:'—'});S.s('hist_'+me.id,h);S.s('w_'+me.id,nw);render();toast('Your check-in has been recorded.')}
P['p-risk']=()=>{const h=hist(),t={l:DB.trend.l,rest:me.rs,load:me.ld};shell('personnel','risk','Risk & Progress',`<div class="g g4">${stat('AI-Assisted Indication',bd(h[0].risk.toUpperCase()),'fa-shield-heart')}${stat('Wellness',W()+'%','fa-heart-pulse')}${stat('Average Rest',(me.rs.reduce((a,b)=>a+b)/5).toFixed(1)+' hours','fa-bed')}${stat('High Workload Days',me.ld.filter(x=>x>=3).length,'fa-briefcase')}</div><div class="g g3"><div class=card><h3>Wellness trend</h3><div class=ch><canvas id=a></canvas></div></div><div class=card><h3>Rest trend (hours)</h3><div class=ch><canvas id=b></canvas></div></div><div class=card><h3>Workload trend (1–4)</h3><div class=ch><canvas id=c></canvas></div></div></div><div class=card><h3>Progress</h3>${tbl(['Date','Wellness','Rest','Workload','Indication','Support'],h.map(x=>[x.d,x.w+'%',x.rest,x.load,bd(x.risk),x.sup]))}</div>`);
 C.line('a',t.l,wTrend());C.line('b',t.l,t.rest,'#14b8a6');C.bar('c',t.l,t.load,'#f59e0b')};
P['p-history']=()=>{const h=hist();shell('personnel','history','Question & Answer History',`<div class=card>${tbl(['Date','Question','Answer','Risk Indication',''],h.flatMap((x,i)=>QA(x).map((q,j)=>[x.d,q[0],q[1],bd(x.risk),`<button class=btn onclick="entry(${i},${j})">View</button>`])))}</div>`)};
P['p-support']=()=>{const r=R.g().filter(x=>x.pid==me.id);shell('personnel','support','Welfare Requests',`<div class=row style="margin-bottom:1rem">${rqBtn}</div><div class="g g2">${r.length?r.map(x=>`<div class="card"><div class="row sp"><b>${x.type}</b>${bd(x.status)}</div><p class=mu>${x.msg||''}</p>${flow(x.status)}</div>`).join(''):'<div class=card>No requests yet. Send one when you need support.</div>'}</div><div class=card><h3>Previous support</h3>${tbl(['Date','Support'],hist().filter(x=>x.sup!='—').map(x=>[x.d,x.sup]))}</div>`)};

/* ---------- Officer ---------- */
P['o-dashboard']=()=>{const p=myReq().filter(x=>x.status=='PENDING'),t=team();shell('officer','dashboard','Welfare '+OFF().n,`<div class="g g4">${stat('Open Requests',p.length,'fa-inbox')}${stat('New Today',p.filter(x=>x.today).length,'fa-bell')}${stat('High Indications',t.filter(x=>x.risk=='High').length,'fa-triangle-exclamation')}${stat('Follow-ups Due',F.g().filter(f=>t.some(y=>y.id==f.pid)&&f.status!='Completed').length,'fa-calendar-check')}</div><div class="card" style="margin-bottom:1rem"><b>${OFF().units.join(' & ')} · ${t.length} personnel · Team check-ins 86%</b></div><h2 style="margin-bottom:1rem">Incoming Welfare Requests</h2><div class="g g2">${p.length?p.map(rc).join(''):'<div class=card>All caught up. No pending requests.</div>'}</div>`)};
P['o-requests']=()=>shell('officer','requests','Incoming Requests',`<div class="g g2">${myReq().map(rc).join('')}</div>`);
const prow=x=>[`<b>${x.n}</b>`,x.id,x.u,x.r,bd(x.risk.toUpperCase()),x.w+'%',x.last,`<a class=btn href="personnel-details.html?id=${x.id}">Open</a>`];
P['o-personnel']=()=>{shell('officer','personnel','Personnel Directory',`<div class=card><div class="g g4"><input id=q placeholder="Search name or ID"><select id=fu><option value="">All units</option><option>Unit A</option><option>Unit B</option><option>Unit C</option></select><select id=fr><option value="">All risk</option><option>Low</option><option>Medium</option><option>High</option></select><select id=fw><option value="">All wellness</option><option value=70>70%+</option><option value=60>60–69%</option><option value=0>Below 60%</option></select></div><div id=tb></div></div>`);
 const f=()=>{const q=$('#q').value.toLowerCase(),w=$('#fw').value;$('#tb').innerHTML=tbl(['Personnel','ID','Unit','Role','Indication','Wellness','Last check-in',''],team().filter(x=>(x.n+x.id).toLowerCase().includes(q)&&(!$('#fu').value||x.u==$('#fu').value)&&(!$('#fr').value||x.risk==$('#fr').value)&&(w===''||(w=='70'?x.w>=70:w=='60'?x.w>=60&&x.w<70:x.w<60))).map(prow))};
 document.querySelectorAll('#q,#fu,#fr,#fw').forEach(e=>e.oninput=f);f()};
function mkFu(id){const p=DB.people.find(x=>x.id==id),f=F.g();f.unshift({id:Date.now(),n:p.n,pid:id,reason:'Officer-created follow-up',created:'Today',due:'In 7 days',status:'Pending'});F.s(f);toast('Follow-up created for '+p.n)}
P['o-personnel-details']=()=>{const id=new URLSearchParams(location.search).get('id')||team()[0].id,p=pp(id)||team()[0],h=hist(p.id);
 shell('officer','personnel',p.n,profile('officer',p,h)+tabs(['Overview','Progress','Q&A History','Support History'],[`<div class=card><h3>Observed pattern</h3><p class=mu>${p.pat}</p></div>`,`<div class=card><div class=ch><canvas id=c1></canvas></div></div>`,qaRows(h),tbl(['Type','Status'],R.g().filter(r=>r.pid==p.id).map(r=>[r.type,bd(r.status)]))]));C.line('c1',DB.trend.l,wTrend(p.id),p.risk=='High'?'#ef4444':'#6366f1')};
P['o-alerts']=()=>shell('officer','alerts','Risk Alerts',`<div class=card>${tbl(['Personnel','AI-assisted indication','Observed pattern','Last check-in',''],team().slice().sort((a,b)=>b.w<a.w?1:-1).map(x=>[`<b>${x.n}</b>`,bd(x.risk.toUpperCase()),x.pat,x.last,`<a class=btn href="personnel-details.html?id=${x.id}">Review</a>`]))}</div>`);
P['o-follow-up']=()=>shell('officer','follow-up','Follow-ups',`<div class=card>${tbl(['Personnel','Reason','Created','Due Date','Status','Action'],F.g().filter(x=>team().some(y=>y.id==x.pid)).map(x=>[`<b>${x.n}</b>`,x.reason,x.created,x.due,bd(x.status),`<button class=btn onclick="fu(${x.id},'Scheduled')">Schedule</button> <button class=btn onclick="fu(${x.id},'Completed')">Complete</button> <a class=btn href="personnel-details.html?id=${x.pid}">View History</a>`]))}</div>`);
function fu(id,s){const f=F.g();f.find(x=>x.id==id).status=s;F.s(f);render();toast('Follow-up '+s.toLowerCase()+'.')}
P['o-analytics']=()=>{shell('officer','analytics','Analytics',`<div class="g g3">${stat('Check-in Completion','86%','fa-clipboard-check')}${stat('Requests Accepted','91%','fa-circle-check')}${stat('Follow-ups Closed','74%','fa-calendar-check')}</div><div class="g g3"><div class=card><h3>Team wellness trend</h3><div class=ch><canvas id=a></canvas></div></div><div class=card><h3>Indication distribution</h3><div class=ch><canvas id=b></canvas></div></div><div class=card><h3>Check-in completion</h3><div class=ch><canvas id=c></canvas></div></div></div><div class="g g2"><div class=card><h3>Welfare requests</h3><div class=ch><canvas id=d></canvas></div></div><div class=card><h3>Follow-up completion</h3><div class=ch><canvas id=e></canvas></div></div></div>`);
 const l=DB.trend.l;C.line('a',l,[64,66,65,69,72]);C.donut('b',['Low','Medium','High'],['Low','Medium','High'].map(k=>team().filter(x=>x.risk==k).length));C.bar('c',l,[74,78,80,83,86]);C.bar('d',l,[9,12,10,14,17],'#6366f1');C.line('e',l,[60,65,68,71,74],'#14b8a6')};

const render=()=>(P[document.body.dataset.page]||(()=>{}))();
render();
